### ISSUE TITLE
Rack::Utils::HeaderHash is deprecated

### ISSUE THREAD

**Issue by tiagomjorge** [ncr/rack-proxy#107]
After bumping out project's rack to 3.0.0, we started seeing this warning message:

```
warning: Rack::Utils::HeaderHash is deprecated and will be removed in Rack 3.1, switch to Rack::Headers
```

Any plans to update rack-proxy's code to switch to `Rack::Headers` and release a new gem? That would be awesome!

**Comment by andneuma** [comment]
Any updates on that issue? We're being flooded with deprecation warnins in one of our projects that we're happy to get rid of. Thanks!
