### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by joaomilho** [ncr/rack-proxy#48]
I've just copied the example w/ example.com, added the "run" instruction, run rackup and... timeout.

```ruby
require 'rack/proxy'

class Foo < Rack::Proxy

  def rewrite_env(env)
    env["HTTP_HOST"] = "example.com"

    env
  end

  def rewrite_response(triplet)
    status, headers, body = triplet

    headers["X-Foo"] = "Bar"

    triplet
  end

end

run Foo.new
```

Any idea?

**Comment by nicolasroy** [comment]
Change the port for the proxied request.
`env['SERVER_PORT'] = '80' if env['SERVER_PORT'].to_i > 1000`
This line above will allow you to request a domain while testing on localhost on a port higher that 1000

**Comment by ncr** [comment]
@joaomilho I hope your issue is resolved by now. Closing this issue.
