### ISSUE TITLE
Licence missing in the rubygems version and in the gemspec

### ISSUE THREAD

**Issue by mensfeld** [ncr/rack-proxy#81]
The "rack-proxy" gem seems not to have a license at all. Unless a license that specifies otherwise is included, nobody else can use, copy, distribute, or modify that library without being at risk of take-downs, shake-downs, or litigation.

I know, that this gem has a license on github, however it's missing one at rubygems and in a gemspec.

![Zrzut ekranu z 2019-04-26 13-36-00](https://user-images.githubusercontent.com/392754/56805118-465d2200-6828-11e9-9918-f19ee3178fc4.png)

**Comment by ncr** [comment]
Fixed
